### ISSUE TITLE
make install fails with "Package @aws-sdk/client-rum does not exist."

### ISSUE THREAD

**Issue by mattcamp** [aws-solutions-library-samples/guidance-for-aws-deepracer-event-management#72]
`make install` fails on a new account during the `drem-backend-main-infrastructure` stack for resource `CwRumLeaderboardAppMonitortest24F3B555`:

`
Received response status [FAILED] from custom resource. Message returned: Package @aws-sdk/client-rum does not exist. (RequestId: 27838284-7faa-4b50-b2e0-f931eb01f8f6)
`

**Comment by StevenAskwith** [comment]
resolved in v2.8.1

**Comment by davidfsmith** [comment]
Still seeing a fail with `Package @aws-sdk/client-rum does not exist` when deploying 2.8.1 for the first time

**Comment by davidfsmith** [comment]
I'm still seeing this issue on a new deployment of DREM

```
Received response status [FAILED] from custom resource. Message returned: Package @aws-sdk/client-rum does not exist
```
